# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Redo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FMDB'
  pod 'SideMenu'
  pod 'Kingfisher', '5.8.0'

  # Pods for Redo

  target 'RedoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedoUITests' do
    # Pods for testing
  end

end
